export const IMAGES = {
 onboardimgbg: require('../Assets/Images/onboardbg.png'),
 Ethical: require('../Assets/Images/Ethical.png'),
 Homebg: require('../Assets/Images/Homebg.png'),
 user:require('../Assets/Images/user.png'),
 doller:require('../Assets/Images/dollerimage.png'),
 everyimage:require('../Assets/Images/everyimage.png'),
 homeimage:require('../Assets/Images/homeimage.png'),
 home2bg:require('../Assets/Images/home2bg.png'),
 Graph:require('../Assets/Images/Graph.png'),
 comunity:require('../Assets/Images/comunity.png'),
 wellcomebg: require('../Assets/Images/wellcomebg.png'),
 loginbg: require('../Assets/Images/loginbg.png'),
Homebg2:require('../Assets/Images/Homebg2.png'),
Homebg3:require('../Assets/Images/Homebg3.png'),
};

export const ICONS = {
  backarrow: require('../Assets/Icons/backarrow.png'),
  Arrow2:require('../Assets/Icons/Arrow2.png'),
  forbesion:require('../Assets/Icons/forbesicon.png'),
  Gibesicon:require('../Assets/Icons/Gibesicon.png'),
  Bell:require('../Assets/Icons/bell.png'),
  microsoft:require('../Assets/Icons/microsoft.png'),
  search:require('../Assets/Icons/search.png'),
  menuicon:require('../Assets/Icons/Menuicon.png'),
  unliver:require('../Assets/Icons/unliver.png'),
  redgraph:require('../Assets/Icons/redgraph.png'),
  downarrow:require('../Assets/Icons/downarrow.png'),
  circular:require('../Assets/Icons/circular.png'),
  Arrow3:require('../Assets/Icons/Arrow3.png'),
  Divest:require('../Assets/Icons/Divest.png'), 
  Social:require('../Assets/Icons/Social.png'),
  Green:require('../Assets/Icons/Green.png'),
  badge1:require('../Assets/Icons/badge1.png'),
  badge2:require('../Assets/Icons/badge2.png'),
  email:require('../Assets/Icons/email.png'),
  Lock:require('../Assets/Icons/Lock.png'),
  eye:require('../Assets/Icons/eye.png'),
  Home:require('../Assets/Icons/Home.png'),
  community:require('../Assets/Icons/community.png'),
  AI:require('../Assets/Icons/AI.png'),
  portfolio:require('../Assets/Icons/portfolio.png'),
  research:require('../Assets/Icons/research.png'),
  greengraph:require('../Assets/Icons/greengraph.png'),
  usericon:require('../Assets/Icons/usericon.png'),
  setting:require('../Assets/Icons/settingicon.png'),
  PowerIcon:require('../Assets/Icons/PowerIcon.png'),
  language:require('../Assets/Icons/languageicon.png'),
  closeicon:require('../Assets/Icons/closeicon.png'),
  logout:require('../Assets/Icons/logout.png'),

};
